chili-epfl/FROG

- frog/imports/ui/Home.app-test.js
- frog/package.json
Currently just checks that the header on the frontpage is what is expected, however this entails compiling and running the entire app, which should catch spelling mistakes etc as well. We should extend in the future. Responds to #29.
> Adding integration test - checks that frontpage renders successfully

- ac/ac-ck-board/package.json
- ac/ac-collab-form/package.json
- ac/ac-form/package.json
- ac/ac-iframe/package.json
- ac/ac-quiz/package.json
- ac/ac-text/package.json
- ac/ac-video/package.json
- circle.yml
- frog-utils/package.json
- frog/.babelrc
- frog/package.json
- initial_setup.sh
- op/op-aggregate-ck-board/package.json
- op/op-aggregate-text/package.json
- op/op-like-with-like/package.json
- package.json
I reorganized the mono-repo to use yarn, and to only install the dev-dependencies once, and symlink them into all the other repositories. 
This approach takes 50 seconds, and results in a total size of 200 MB. The old approach takes 4 minutes, and generates 560 MB of data. Note that this will only increase once we add twenty more operators and activities etc :)
I couldn't figure out how to check for the presence of a binary, but this script should also work perfectly well with npm instead of yarn, so could you add a test that it uses npm if yarn is not installed?
> Using yarn and symlinks to decrease install time and size

- ac/ac-collab-form/src/dashboard.js
- frog-utils/src/TimedComponent.js
- frog-utils/src/index.js
- initial_setup.sh
- run_and_watch_all.sh
Assuming that we might have a number of components that need to regularly update, but don't otherwise require component lifecycle methods, this Higher-Order Component can wrap a pure component providing the timeNow prop, which will update at a regular interval, thus making repeated rendering very easy. This is currently used for a dashboard with fading colors, but could also be used for Khalil's orchestration clock, etc.
> TimedComponent

- frog/imports/ui/GraphEditor/Activities.js
- frog/imports/ui/GraphEditor/store/activity.js
- frog/imports/ui/GraphEditor/store/activityStore.js
- frog/imports/ui/GraphEditor/store/store.js
- frog/imports/ui/GraphEditor/utils/index.js
Graph startTime is always an integer (not float), which should help with activity alignment. Activities should not be above each other when they don't need to, and dragging activities "across" (swap) should work better. The activity swap still needs better UI feedback, but at least it should be fully functional.
> Fix graph movement

- frog/imports/ui/GraphEditor/Graph.js
- frog/imports/ui/GraphEditor/index.js
- frog/imports/ui/GraphEditor/store/uiStore.js
- Only allows keyboard shortcuts while mouse is over main graph (not minimap)
- Filters keyboard shortcuts with Cmd etc (to avoid Cmd-P for printing triggering operator)
- Avoid default, to avoid both creating operator and entering into the rename field, if rename field is active
> This fixes some bugs with keyboard shortcuts

- frog/imports/ui/GraphEditor/store/store.js
I turned state into a setter and getter, which checks whether store is read-only or not. All actions check whether
they are in the correct "mode", so this basically makes the entire store read-only (or not). 
To test, change new Store() to new Store(true) in /store/index.js
> Making it possible to create read only graph store

- frog/imports/ui/GraphEditor/EditorContainer.js
When changing tabs, the graph editor splitpanes was reseting itself to 1000px, while the store still has store the previous changed size
> Initialize splitPane width to be store.ui.graphWidth

- frog/imports/ui/GraphEditor/Graph.js
We should still fix how drag guides are rendered with allowOverlap
> Putting dragGuide under activities, fixing #114

- .eslintrc.js
- frog/imports/ui/App.jsx
- frog/imports/ui/GraphEditor/fixedComponents.js
- frog/imports/ui/GraphEditor/store/store.js
In the future we might add something more complex, but for now this works reasonably well - it updates the address bar when you switch to another app (tab), and checks the URL bar on startup/change to update the route. This let's us be in localhost:3000/graph, and on reload, it will put us straight back into graph. 
Right now the logic with switchAppByUser is a bit convoluted - it checks whether the user has entered something in the URL bar, and then uses that (unless not logged in), otherwise uses the result of switchAppByUser. I'm not sure if we even need that anymore... Anyway we eventually want to separate out the logic for students, from that for teachers completely. (Ie users should not see the bar, etc).;wq
> Adding address bar routing for apps

- frog/imports/ui/GraphEditor/Activities.js
This hides the text and circle if the activity is too small, avoiding JS errors resulting from width - 20, when width is < 20, etc.
> Don't show activity internal elements if small

- frog/client/main.css
- frog/imports/ui/GraphEditor/SidePanel/ActivityPanel.js
- frog/imports/ui/GraphEditor/TopPanel/GraphConfigPanel.jsx
- frog/imports/ui/GraphEditor/TopPanel/GraphList.jsx
- frog/imports/ui/GraphEditor/TopPanel/Settings.js
- frog/imports/ui/GraphEditor/TopPanel/index.js
- frog/imports/ui/GraphEditor/store/store.js
- frog/imports/ui/GraphEditor/utils/TextInput.js
- frog/imports/ui/GraphEditor/utils/export.js
- frog/imports/ui/GraphEditor/utils/exportPicture.js
I tried cleaning up the menu bar in the graph editor a bit, which had grown by us gradually adding options with no clear design :) I made another dropdown with most of the options and operations, and made the title and time similar to the rename in sidebar - click to edit. This also means we avoid issues about graph length jumping around while we're typing. (Also, you had forgotten to write graphLength to the database :))...
The code is pretty ugly, and could probably use a refactoring, but everything should work - except duplicateGraph - it doesn't look like this was working in your version either? Did we have a function for this at some point which disappeared?
We should think a bit about consistent approach to theming... right now we have both a main.css, bootstrap, react-bootstrap …
> Cleaning up graph menubar

- frog/imports/ui/GraphEditor/store/activity.js
- frog/imports/ui/GraphEditor/store/activityStore.js
I think I caught it - amazingly we were not Math.rounding the location of new activities added by double-clicking, but instead we had so many Math.rounds in other places. If this problem ever reappears, please file a bug. :) Fixes #116.
> Ensuring activity startTime is always integer

- op/op-like-with-like/.babelrc
- op/op-like-with-like/package.json
- op/op-like-with-like/src/index.test.js
- package.json
- yarn.lock
First attempt at adding simple unit tests with Jest. Here's what we need to make it work
- installing Jest globally (done by PR)
- .babelrc file needs to be added to each package (example in PR)
- very simple test script added to package.json (not strictly necessary, can run from command line)
- write tests, example in this PR
This is the simplest example, we can for example have a list of expected input and output and loop over the array to test all inputs to outputs. If we trust that the operator is working well, we can also have a bunch of inputs, and then just capture the outputs automatically - then it will let us know if the outputs ever change in the future (upgrading packages, fixing bugs etc). 
It's very fast, and you can run it in watch mode (./node_modules/.bin/jest --watch), …
> Adding jest, and example test

- initial_setup_wo_meteor.sh
I had trouble installing FROG on both my macbook and Ubuntu desktop because of this line that was removed. It makes the bash commands include hidden files.
> Re-include hidden files in initial_setup

- frog/imports/ui/GraphEditor/index.js
- frog/imports/ui/GraphEditor/store/activityStore.js
This adds keyboard commands to the graph editor, to quickly create new activities that have the same length as the current activity. Given a currently selected activity, 'a' adds the activity on the same plane, and 1/2/3 adds an activity on the desired plane. This seems to be a common need when designing graphs with multiple concurrent activities. Only start-time and end-time is copied, not title/acType, etc.
> Adding command a to copy existing activity length

- op/op-create-groups/src/__tests__/index.js
- op/op-create-groups/src/index.js
There was a bug that led to settings: size 2, strategy: min to generate one group of 4. Fixed, and added test.
> Fixing op-create-groups

- frog/imports/ui/StudentView/Runner.jsx
This is quite an egregious bug, that harks back to your switching from an array to an Object for doGetInstances. Of course, it would have been better for JS to just complain that you're doing [1] on an object, but instead we just silently get undefined, and the error ends up much later down the stack. I'm actually quite surprised that Flow didn't catch this, the files are all flow-checked.
> Fixing Runner

- frog/imports/ui/GraphEditor/utils/export.js
This assigns new IDs, and clears the sessionId field. I had a case where a graph had been exported as a session, and when importing it, I was not able to start a new session based on it. 
(In the future, we will have true "export session" stuff, and we also want to make it easier to move between "graph" and "session", but for now, this is what we'd expect when importing a graph)
> Making sure imported graphs work properly

- frog/imports/ui/GraphEditor/utils/export.js
Removes sessionId and state from activities/operators, and makes the resulting filename nicer, reflecting the name of the graph, and a custom extension (since you cannot load random .json into FROG, despite the save-format being JSON-based).
> Improving graph export

- frog/imports/ui/App/Navigation.jsx
- frog/imports/ui/App/index.js
- frog/imports/ui/GraphEditor/utils/export.js
- frog/imports/ui/StudentView/Runner.jsx
- frog/imports/ui/StudentView/SessionBody.jsx
Ref #302. This makes URLs the only way to log in, and reverses the order (username, then app). Teacher status is set by username === 'teacher' (for now). Teacher sees navigation bar, and the apps in the URL bar are taken into account. Other users go directly to student view, and do not see the navigation bar.
It also removes the layout chrome for single activities in Runner... Not sure if this is desirable - you loose the title and the grouping info which is useful for debug, but you have more flexibility for custom layout etc.
> Removing navigation bar for students, and chrome for single activities

- frog/imports/ui/StudentView/Runner.jsx
- frog/imports/ui/StudentView/SessionBody.jsx
- When starting with an activity on individual plane, studentView was not updated automatically when teacher clicked start. It was actually crashing with `cannot access studentIds of undefined at doGetInstances`
`if(!object){...}` was doing `...` even when `object = {}`. Indeed ` !{} === false`
small fix about the no activity state when `session.openActivities` is not undefined but an empty list (again `![] === false` )
> Fix empty object bug in Runner

- frog/imports/api/__tests__/validGraphFnTest.js
- frog/imports/api/validGraphFn.js
- frog/imports/ui/GraphEditor/Activities.js
- frog/imports/ui/GraphEditor/Operator.js
- frog/imports/ui/GraphEditor/Operators.js
- frog/imports/ui/GraphEditor/store/elemClass.js
- I added a type to each error, and also checking whether operators have at least one outgoing connection.
- I changed the border drawing of AC/OP. Rather than switching between normal color and highlight, the highlight is now drawn outside the basic color, giving us more choice with the basic color.
- I distinguish between an ac/op not yet specified, by fading the color. This makes it visually clear that the ac/op has not been specified, without screaming error (as the designer is still in the process). Once the ac/op has been specified, it changes color to either a solid dark, if correct, or red, if there is one or more errors attached to that object.
> Adding highlighting of erroneous ac/op

- frog/imports/api/sessions.js
- frog/imports/api/validGraphFn.js
- frog/imports/ui/GraphEditor/Validator.js
- frog/imports/ui/GraphEditor/store/store.js
- frog/imports/ui/GraphEditor/store/uiStore.js
- frog/imports/ui/TeacherView/index.js
This PR adds a distinction in severity. Conditions which will cause engine errors are 'error', things that will not cause errors, but are superfluous or possible mistakes are 'warning'. Currently, the only errors marked warning are related to operators with no connections - this does not cause an error, and whether they are fully configured or not, is irrelevant. However, it's most likely a mistake, which is why we're highlighting it.
The circle is red if there are any errors, and yellow if only warnings. I also ensure that you cannot initiate a graph in the engine if it has any errors (warnings are OK).
> Adding warning/error distinction

- ac/ac-brainstorm/src/index.js
- ac/ac-chat/src/index.js
- ac/ac-ck-board/src/index.js
- ac/ac-form/src/index.js
- ac/ac-iframe/src/index.js
- ac/ac-induction/src/index.js
- ac/ac-quiz/src/index.js
- ac/ac-text/src/index.js
- ac/ac-video/src/index.js
- frog/imports/api/sessions.js
- frog/imports/ui/GraphEditor/SidePanel/ActivityPanel.js
- frog/imports/ui/GraphEditor/SidePanel/ListComponent.jsx
- frog/imports/ui/GraphEditor/SidePanel/OperatorPanel.js
- op/op-argue/src/index.js
- op/op-create-groups/src/index.js
- op/op-distribute/src/index.js
- op/op-group-identical/src/index.js
- op/op-hypothesis/src/index.js
- op/op-jigsaw/src/index.js
This PR
- improves the look of the list a bit, by using bootstrap Button instead of button, etc.
- now, you can only expand items, expanding an item collapses all other items
Still not perfect, but seems cleaner to me.
Note the use of recompose to add state to a stateless component. I just don't like classes :) We use this a few other places, including the withVisibility function from frog-utils :)
Also updated/expanded on the descriptions in all ac/op packages.
> Better ac/op list

- frog-utils/src/__tests__/index.js
- frog-utils/src/index.js
- frog/imports/activityTypes.js
- frog/imports/operatorTypes.js
This will make it easier to have a package with many short operator functions for example, and also speed up development (adding a new operator is caught automatically, without adding lot's of links and directories etc).
> Enabling ac/op packages to export multiple op/ac

- frog-utils/package.json
- frog-utils/src/EnhancedForm.js
- frog-utils/src/index.js
- frog-utils/yarn.lock
- frog/imports/ui/GraphEditor/SidePanel/ActivityPanel.js
- frog/imports/ui/GraphEditor/SidePanel/OperatorPanel.js
- op/op-distribute/src/index.js
This PR adds a wrapper around react-jsonschema-form, EnhancedForm in frog-utils. The wrapper recognizes a conditional field, either as a string (if the other field is true), or as a function, taking formData as input. Example:
```js
UISchema: {
username: { 
conditional: 'hasUsername'
}
seniorDiscount: { 
conditional: formdata => formdata.age > 67 
}
}
```
Currently, both operator and activity sidepanels use this enhanced form. For now, I'm using activity/operatorType.configUI to store the UISchema, to avoid rewriting every ac/op. In the future, we might change config to have schema, and UISchema, or something like that.
Currently, data is still stored and kept whether a field is visible or not. Not sure if making a field invisible should remove the data from the invisible field.
All other …
> Adding conditional fields in forms

- ac/ac-brainstorm/src/index.js
- ac/ac-chat/src/index.js
- ac/ac-ck-board/src/index.js
- ac/ac-form/src/index.js
- ac/ac-iframe/src/index.js
- ac/ac-induction/src/index.js
- ac/ac-quiz/src/index.js
- ac/ac-text/src/index.js
- ac/ac-video/src/index.js
- frog-utils/src/types.js
- frog/imports/api/activities.js
- op/op-argue/src/index.js
- op/op-create-groups/src/index.js
- op/op-distribute/src/index.js
- op/op-group-identical/src/index.js
- op/op-hypothesis/src/index.js
- op/op-jigsaw/src/index.js
Social operators and product operators have some different values, and  we need Flow to be able to detect this properly. Turns out that currently it can only do so if the variable to check is in the top level of the object, see contrasting examples:
- [Doesn't work](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCmAPADrATgF1LgJ4YqgCCAxrgJYBu1RAIgEYAqoAvKAN6KigB9agBMAXKADOubNQB2AcwA0fUMICGuNeIDyzAFYoqy-vOywArhjnyA0ikLipMhcdAZoa2SnGzzAW2YUbEQAXwBuZBAeUDUtaNMLDHEARkVQM2hvUAByCgALFEhstIpYOGxxbOwUYWzQEOUo-mZmcW5QBMtxACY0jKzs+DUGILqGxCbQCgo29LKBoZHsMfrUTBx8IhJJXHNhFFlcAGVpcypzavYuXn4AbSk9g9wASTEd53kAXVnbjWlqZjmXAoOwOd7Wb7ghSrcKRMDtTpJaLZZLZcS3HKxHKgT5pbLdNGgDHZFp1T71Rpgfj9Wb5QrozFqMlpRbAipEnKkvHTMkUiZUqZlHCzapvbKxFYhNZYPAEYikCSwCjUNTQE7YM67S6cHgqX64f6A4Ggxz-BSQm78Il-GRGlAANVV5iyTghpo+t0+KilsOlGzl23UmgA …
> Moving types to top-level in ac/op

- ac/ac-brainstorm/src/config.js
- frog-utils/src/index.js
- frog/imports/ui/GraphEditor/SidePanel/ActivityPanel/EditActivity.js
- frog/imports/ui/GraphEditor/SidePanel/OperatorPanel.js
- frog/imports/ui/GraphEditor/Validator.js
- frog/imports/ui/GraphEditor/store/uiStore.js
This enables showing the ValidButton and error bubbles in the sidebar of operator/activity (filtered for that op/ac). Necessary for the form validation I will be adding.
Code is getting a bit ugly, should be refactored at some point (both Valid.js, and the ac/op sidebar - nice how I split ac into several files, op is still long. But could also look at whether similar code could be shared).
> Showing error bubbles in sidebar

- ac/ac-form/src/config.js
- ac/ac-form/src/index.js
- frog-utils/src/EnhancedForm.js
- frog-utils/src/index.js
- frog-utils/src/types.js
- frog/imports/api/__tests__/validGraphFnTest.js
- frog/imports/api/__tests__/validSocial.js
- frog/imports/api/__tests__/validateConfig.js
- frog/imports/api/checkSocial.js
- frog/imports/api/traceSocial.js
- frog/imports/api/validGraphFn.js
- frog/imports/api/validateConfig.js
- frog/imports/ui/GraphEditor/SidePanel/ActivityPanel/EditActivity.js
- frog/imports/ui/GraphEditor/SidePanel/OperatorPanel.js
- frog/imports/ui/GraphEditor/Validator.js
- frog/package.json
- frog/yarn.lock
- op/op-hypothesis/src/index.js
This adds config validation to both operators and activities, using jsonschema, and a custom validateConfig function. It also changes the formatting of error messages to insert nodeType and name globally, which means that we can hide this in the sidepanel error list.
> Validate config

- ac/ac-ck-board/src/index.js
- frog/imports/ui/GraphEditor/Preview.js
- frog/imports/ui/GraphEditor/SidePanel/ActivityPanel/EditActivity.js
- frog/imports/ui/StudentView/ReactiveHOC.jsx
This PR adds the ability to show a preview of an activity, given user inputted custom config. This option is only valid when there are no errors for a given activity. It chooses all exampleData configs where the activityData portion is different, and merges the config into the activityData object.
Future note:
Currently the example data mix config and activity data. This makes it messy when we try to provide different example data in activity-specific preview... One option is to disentangle, provide one list of activityData, and one list of config... Makes preview UI a bit more complex, and also - do all configs go with all example data? So far, I think so?
> Preview based on custom config

- ac/ac-chat/src/index.js
- frog-utils/src/dataStructureTools.js
- frog/server/runDataflow.js
I think the cleanest approach is to make incoming empty data explicitly null, and have activities explicitly check for null. This only needs to happen in mergeFunction, because the reactive data is initialized with the default dataStructure ([] or {} or something else), so the actual ActivityRunner can map, etc without worry. 
Needs more testing with the other activities/operators. 
Closes #400 
Closes #309
> Default incoming data -> null

- frog-utils/src/index.js
- frog-utils/src/types.js
- frog/imports/ui/App/FROGRouter.js
- frog/imports/ui/App/TopBar.js
- frog/imports/ui/GraphEditor/Preview.js
- frog/imports/ui/Preview/index.js
- frog/imports/ui/StudentView/ReactiveHOC.jsx
This enables previewing activities outside of the context of the graph editor, with a permanent URL that survives reloads. 
- you can directly type /preview/{activity-id} optionally followed by {example-id}. It also keeps track of whether showing data with ?showData=true
- you can click on preview in the top menubar (or just type /preview) to see a list of all activity types. This list is also shown if you close an activity preview
- when previewing an activity in the graph editor, there is a link to open the preview with a permanent URL (note, you cannot get back to the graph view from here)
This seems to work quite well with minimal code change. In the future, I could imagine adding the possibility of custom configurations, as well as the ability to see an activity inside a multi-window …
> Preview on separate permanent URL

- frog/imports/ui/GraphEditor/Preview.js
- frog/imports/ui/StudentView/ReactiveHOC.jsx
- frog/imports/ui/StudentView/Runner.jsx
This makes the Preview reactive data structure live in memory, and adds a button to reset the data. Since it's in memory, it's automatically reset on reload as well, of course.
Closes #382
> Fix reactive data (second attempt)

- ac/ac-imgView/src/ActivityRunner.jsx
- ac/ac-imgView/src/Dashboard.jsx
- ac/ac-imgView/src/components/UploadBar.jsx
- ac/ac-imgView/src/components/UploadDragDrop.jsx
- ac/ac-imgView/src/index.js
- frog-utils/src/types.js
- frog/imports/api/logs.js
- frog/imports/ui/StudentView/Runner.jsx
- frog/imports/ui/StudentView/SessionBody.jsx
- frog/imports/ui/TeacherView/Dashboard.jsx
- frog/imports/ui/TeacherView/index.js
- frog/server/mergeData.js
- frog/server/mergeLogData.js
- New field for in `ActivityPackageT` for dashboards
```JavaScript
{
...,
dashboard: { 
Viewer: ReactComponent,
mergeLog: Function,
initData: any
},
...
}
```
- An example of dashboard on `ac-imgView` counting number of votes and number of uploads. No visualization, data pipeline only.
- In `server/mergeData` creates the document for the logs and initialise it with the `initData`
- in `server/mergeLogData` implement `Meteor.Method({'merge.log': ... }]` called from the loggers
- A component to navigate between the available dashboards when several activities are open
- Removes the possibility of filtering selected activities (just like categories are filtered) in `ac-imgView`. It was badly implemented and was creating bugs. It can be easily re-implemented. This PR was already big enough!
- …
> Update the ActivityPackage dashboard API

- frog/imports/api/graphs.js
- frog/imports/api/sessions.js
- frog/imports/ui/GraphEditor/utils/export.js
I have a new function, addGraph in api/graphs, which takes an object with graph, activities, operators, connections, or empty. If empty, it just creates a new unnamed graph. If not, it does all the copying logic (updating ids in connections etc). It does all the updating of act/op/conn in memory, before writing the final version to Mongo (the previous case, we first wrote to Mongo, then updated the connections in the database through a loop).
Now the same logic is used for copying a graph when creating a session, in the graph editor, and when importing a graph. This makes it easier to add new logic in the future.
> Unifying copying/adding graph

- frog/imports/ui/GraphEditor/Preview.js
- frog/imports/ui/Preview/index.js
This PR adds to improvements to Preview
- The size of the activity should now fit into the preview box without scrolling (if it is a full-screen activity, using height: 100% etc). This has been tested with a few different activities.
- There is now the possibility to see how an activity would look with multiple other activities. There are win+ and win- buttons, incrementing/decrementing the number of windows. 
Known issues:
- sometimes when rapidly adding/removing windows, I get eventEmitter errors. I don't think this is a big issue though. 
- somehow the buttons in Mosaic don't render properly anymore. However, this is the case even when running a script, so I don't think it's related to this PR.
> Improving Preview

- frog/imports/ui/GraphEditor/SidePanel/ConfigForm.jsx
This PR tries to address the following issue:
- conditional fields do not trigger while a form is in focus
while preserving:
- editing within a string does not jump to the end
- deleting a default value is not impossible
It does this by keeping formData in local state, which means it always runs through the proper functions (conditional etc), but is not reset unless the user is switching to a different node. This means that it does not listen to changes from the database.
(I know I said we should not keep props in state, but in this case I think it makes sense).
Closes #469
> Fixing ac/op side-panel editing behaviour

- ac/ac-video/src/dashboard.js
- ac/ac-video/src/index.js
- frog/imports/ui/TeacherView/Dashboard.jsx
- frog/imports/ui/TeacherView/index.js
This updates the ac-video dashboard to work with the current API. I also added users ({userId: username}) to the argument that Viewer is called with - we can discuss about what other information the Viewer should have access to. 
I'm still figuring out how to most efficiently work with reactive data, but the function I wrote to merge objects, while checking whether the object already exists, might be wrapped in a general function and used elsewhere. Note that I'm starting just with an empty {} in initData. Also, I noticed that shareDB batches the several operations done for an incoming log entry, and sends them all in bulk (and this work is done on the server anyway of course, although the update is then sent to the teacher client). 
Issues:
- if you toggle the dashboard on and off, you …
> Updating ac-video dashboard

- frog/imports/ui/TeacherView/Dashboard.jsx
This should fix the setState error, and has been confirmed to work with the imgView dashboard.
Closes #486
> Fix preview of dashboard

- ac/ac-quiz/src/ActivityRunner.jsx
Currently the ac-quiz stores answers as numbers, but the definition asks for strings, which leads to conflict when trying to submit.
> Fixing form definition of ac-quiz

- frog/imports/ui/App/index.js
This fixes the issue that admin would get logged out when reloading in preview, because it only checked for query parameters, not the login parameter, and Preview users query parameters as well.
> Avoid logging out admin in Preview

- frog-utils/package.json
- frog-utils/src/generateReactiveFn.js
- frog-utils/src/index.js
- yarn.lock
This PR adds collaborative editing. It adds a bindTextField method to dataFn, which receives a ref and a path. It needs to be destroyed on unmounting.
To take care of this (ref, destroy etc), we expose a ReactiveText from frog-utils, which take dataFn and path and type (textarea/textfield), and takes care of everything else. I have tested that it works fine when changing props, changing activity, etc.
> Collaborative editing

- frog/imports/ui/App/NotLoggedIn.js
- frog/imports/ui/App/index.js
We used to have a "nice" message when a developer opened FROG without logging in, but it disappeared when rewriting the login sequence. I put it back, and made it even nicer :) I think this is important, as there are more and more people installing FROG for the first time, and it doesn't feel very welcoming to see "You are not logged in" when booting. I have verified that this is not displayed in production mode.
> Making developer not-logged-in message more friendly
