chili-epfl/FROG

frog/imports/ui/App.jsx
frog/imports/ui/StudentView.jsx
frog/imports/ui/TeacherView.jsx
frog/server/main.js

We will probably have a much better system in the future, but for now I think it makes development a bit easier. It basically checks if the user is called 'teacher', and if so, forwards him/her to the teacherview. If not, forwards him/her to the studentview.
(note that because the collections are not synced immediately, I had to learn a bit about publication and waiting for a publication to be ready, to implement this - which is useful in general).

Automatically sending student and teacher to different views

---

frog/imports/api/graphs.js
frog/imports/ui/svg/Graph.js
frog/imports/ui/svg/GraphList.jsx
frog/imports/ui/svg/Rename.js
frog/imports/ui/svg/constants/index.js
frog/imports/ui/svg/index.js
frog/imports/ui/svg/store/store.js

Add graph list next to graph editor and allow saving multiple graphs

Graph list

---

frog/imports/ui/svg/GraphConfigPanel.jsx
frog/imports/ui/svg/GraphList.jsx
frog/imports/ui/svg/fixed_components.js
frog/imports/ui/svg/index.js

I added very nice colors to understand better the layout. Now we have blocks on top, left, right and bottom of the main editor that we will be able to use for different action/configuration.

Add new panel over the graph for configuring the graph name.

---

frog/imports/ui/GraphEditor/GraphConfigPanel.jsx
frog/imports/ui/GraphEditor/GraphList.jsx
frog/imports/ui/GraphEditor/store/store.js

#92 
- Fixes the bug with rename, due to renaming in store of `id` to `graphID`. I named it everywhere `graphId`.
- Uses drop-down button for graph selection

Reduce size of graphListPanel to have only four buttons with a dropdown

---

frog/imports/ui/GraphEditor/EditorContainer.js
frog/imports/ui/GraphEditor/Graph.js
frog/imports/ui/GraphEditor/HelpModal.js
frog/imports/ui/GraphEditor/index.js
frog/imports/ui/GraphEditor/store/uiStore.js
frog/package.json

The modal is pulled up with '?'. We can adapt the text going forwards.
We could also automatically show the modal the first time a user is
editing a graph (not currently the case).

This adds a help modal for the graph editor

---

frog/client/main.css
frog/imports/ui/App.jsx

- Removes old CSS code for Jsplumb
- Aligns the login button with the navigation bar
- Uses `react-bootstrp.Nav` for the navigation bar

Layout of login button

---

frog/imports/ui/GraphEditor/store/store.js

The bug with sticky was not only on deleting a graph, but also on changing graphs and on deleting the activity

Fix bugs with sticky sticking too much

---

frog/imports/ui/GraphEditor/DragGuides.js
frog/imports/ui/GraphEditor/store/activityStore.js

- uses endTime instead of start+length
- computes a min and a max instead of sorting (more efficient)
- still display guides when distance is 0. I find it nicer. Do you have a strong opinion against it?

Fix selection of right and left bounds activities

---

frog/imports/ui/GraphEditor/store/store.js
frog/imports/ui/GraphEditor/store/uiStore.js

Updates scale and pan when changing the graph duration to have a fixed view 

---

frog/imports/ui/GraphEditor/store/uiStore.js

Even if the graphDuration is very high.

Making it possible to zoom all the way in

---

frog/imports/ui/GraphEditor/Rename.js
frog/imports/ui/GraphEditor/store/uiStore.js

This fixes the drag zone, so that it works for activities, but it also properly displays activities and connecting lines while dragging, not just when moving the mouse up and down. Fixes #112.

DraggingZone working again

---

frog-utils/src/index.js
frog/imports/ui/Admin.jsx
frog/imports/ui/GraphEditor/SidePanel/ActivityPanel.js
frog/imports/ui/GraphEditor/SidePanel/OperatorPanel.js
frog/imports/ui/TeacherView/SessionList.jsx

Introducing A for cleaner links

---

ac/ac-jigsaw/src/ActivityRunner.jsx
ac/ac-jigsaw/yarn.lock
frog/imports/ui/App.jsx

I did not find a way to have many user connected within the same browser.

Creates and log in a user with default password from url

---

frog/imports/api/sessions.js
frog/imports/ui/GraphEditor/EditorContainer.js
frog/imports/ui/GraphEditor/Graph.js
frog/imports/ui/GraphEditor/store/activity.js
frog/imports/ui/GraphEditor/store/activityStore.js
frog/imports/ui/GraphEditor/store/uiStore.js
frog/imports/ui/TeacherView/ActivityList.jsx
frog/imports/ui/TeacherView/GraphView.jsx
frog/imports/ui/TeacherView/index.js

- Fix a few bugs on the readonly editor
- Fix buggy resizing of the graph editor
- gives graphId to the activities copied for a session

Add readOnly graph in TeacherView

---

frog/imports/api/activities.js
frog/imports/api/sessions.js

Delete session/copied graph when copied graph/session is deleted

---

frog/imports/ui/GraphEditor/EditorContainer.js
frog/imports/ui/GraphEditor/Graph.js
frog/imports/ui/TeacherView/GraphView.jsx
frog/imports/ui/TeacherView/index.js

Before, using the `<Graph>` required to give it the correct props `width, height, viewBox` with no choice, so I moved these useless props inside the component.

Simplify the logic of the Graph component

---

frog-utils/src/TextInput.js
frog/imports/ui/GraphEditor/SidePanel/ActivityPanel.js
frog/imports/ui/GraphEditor/SidePanel/OperatorPanel.js
frog/imports/ui/GraphEditor/store/operator.js

This PR makes ChangeableText respond to new props, without needing an ID, and fixes the TopMenu components, which did not properly update before. I also update the operator sidebar to use ChangeableText, to simplify code.

Cleaning up ChangeableText

---

frog/imports/api/graphs.js
frog/imports/ui/GraphEditor/TopPanel/Settings.js
frog/imports/ui/GraphEditor/utils/export.js

Using code for export and import, which ensures unique IDs etc. Also fix that graph length was not preserved on export/import. Fixes #190.

Fixing duplication of graphs

---

frog/imports/api/graphs.js
frog/imports/api/sessions.js
frog/imports/ui/Admin.jsx

#202 
Also fixes bug where activities were not deleted when the session and graph were deleted

Fix bug #202 Spurious activities

---

initial_setup.sh

fixes install under a dir with spaces

---

run_and_watch_all.sh

I often already have meteor running, and want to switch this on. This makes it more flexible.

Removing meteor from run and watch all

---

frog/imports/api/__tests__/doGetInstances.js
frog/imports/ui/GraphEditor/store/activity.js
frog/imports/ui/GraphEditor/store/activityStore.js
frog/imports/ui/GraphEditor/store/connection.js
frog/imports/ui/GraphEditor/store/connectionStore.js
frog/imports/ui/GraphEditor/store/elemClass.js
frog/imports/ui/GraphEditor/store/operator.js
frog/imports/ui/GraphEditor/store/operatorStore.js
frog/imports/ui/GraphEditor/store/session.js
frog/imports/ui/GraphEditor/store/store.js
frog/imports/ui/GraphEditor/store/uiStore.js

This is the result of running the latest Prettier. I don't love the formatting of decorators, but that's what they've decided, and we want to stay with Prettier - it's not the end of the world :)

Upgrading Prettier formatting

---

frog/imports/ui/GraphEditor/utils/export.js

This is the beginning of making FROG more crash-proof. Try uploading a PDF file, you get an error (in the future we can have nicer error messages etc, but it's not so important), and the program continues without any issues.

Showing error message if importing faulty graph

---

frog/imports/api/graphs.js

This will be superceded by knowing which groupingKeys are made available by upstream operators, but for now it makes editing much smoother.
It's a bit awkward where I put the code, but the alternative would be to add a new field to the MobX store, which requires updating in a bunch of places.

Making groupingKey "group" the default

---

frog/imports/api/activities.js
frog/imports/ui/StudentView/Runner.jsx
frog/server/mergeData.js
frog/server/reactiveToProduct.js

getInstances wasn't doing any useful job anymore

Removing getInstances, and switching to doGetInstances directly

---

README.md

Update README.md with info about yarn/npm

---

ac/ac-induction/package.json
ac/ac-induction/src/Images.jsx
ac/ac-induction/src/Induction.jsx
ac/ac-induction/src/Rules.jsx

@agentromain I reviewed your code for ac-induction and made modifications to it that I think make the code a lot nicer. Give it a look.

Improve style in ac-induction style

---

frog/imports/ui/App/Body.jsx

Adding some helpful info, useful for people downloading themselves to try it out.

Updating frontpage

---

frog/imports/ui/App/Body.jsx

Nicer frontpage with login links

---

frog/.meteor/packages
frog/.meteor/versions
frog/imports/ui/App/index.js
frog/server/main.js

removed the autopublish, published in the server/main and subscribed …in the ui/App depending on who's the user.
Meteor doesn't send me any error, eslint & flow pass.

removing autopublish

---

frog/imports/api/__tests__/validGraphFnTest.js
frog/imports/api/validGraphFn.js

One quick thing was to move all the test fixtures to the bottom (they get hoisted, so they are still in scope), to make the test file easier to work with.
Then I tried to rewrite your functions to be more "functional", with no more mutable variables and for-loops... In the end, we want to add more kinds of tests, and we will probably restructure it quite a bit anyway, but for now all your tests are passing - see if I am missing anything. I need to review the graph editor code etc tomorrow.
(Your tests made the rewrite much nicer - I only used jestWatch, and didn't open Meteor a single time. Of course, if the test pass and it still doesn't work in Meteor, it means you didn't write specific enough tests :))

Making it functional

---

frog/imports/ui/GraphEditor/SidePanel/ActivityPanel.js
frog/imports/ui/GraphEditor/SidePanel/OperatorPanel.js

Search tool

---

templates/activity/package.json
templates/activity/src/index.js
templates/activity/yarn.lock

Updating dependencies, adding descriptions, and some comments.

Updating activity template with description etc

---

frog/imports/ui/GraphEditor/SidePanel/ActivityPanel.js
frog/imports/ui/GraphEditor/SidePanel/ListComponent.jsx

Only showing preview when there is something to preview

---

frog/imports/api/validGraphFn.js

This is some pathological code for Flow, and adding annotations makes Flow work again. https://github.com/facebook/flow/issues/4370

Fixing Flow inference

---

frog/imports/ui/GraphEditor/index.js

This avoids the 'w' ending up in the side searchbar

---

frog-utils/src/EnhancedForm.js
frog-utils/src/types.js
frog/client/stylesheets/flexView.css
frog/imports/api/__tests__/traceSocial.js
frog/imports/api/__tests__/validGraphFnTest.js
frog/imports/api/sessions.js
frog/imports/api/traceSocial.js
frog/imports/api/validGraphFn.js
frog/imports/ui/GraphEditor/SidePanel/ActivityPanel.js
frog/imports/ui/GraphEditor/SidePanel/OperatorPanel.js
frog/imports/ui/GraphEditor/store/store.js
frog/package.json
frog/yarn.lock
op/op-argue/src/index.js
op/op-create-groups/src/index.js
op/op-group-identical/src/index.js
op/op-jigsaw/src/index.js

Adds function to calculate which social attributes are available to activities (social operators have to declare their output, either statically, or as a function of the config data), and the activity sidepanel has a drop-down to select available attributes.

Interface for selecting social attributes in activity selector

---

frog-utils/src/EnhancedForm.js
frog/imports/api/__tests__/traceSocial.js
frog/imports/api/__tests__/validGraphFnTest.js
frog/imports/api/__tests__/validSocial.js
frog/imports/api/checkSocial.js
frog/imports/api/traceSocial.js
frog/imports/api/validGraphFn.js
frog/imports/ui/GraphEditor/SidePanel/ActivityPanel/EditActivity.js

Add checks against both groupingKey as well as any socialAttributes in the configuration of operators or activities.

Validate socialAttributes

---

ac/ac-brainstorm/src/ActivityRunner.jsx
ac/ac-brainstorm/src/index.js

- in brainstorm each student can now only vote once for each idea 
- color for thumb up/down icons
- some restructuring for legibility

Improving ac-brainstorm

---

frog/imports/ui/StudentView/index.js

solve a small bug that appeared in imagClassifier, I tested all activities, don't seems to create any other problem

set Height and Wdth of div student to 100%

---

ac/ac-prox/src/index.js
frog/imports/api/validateConfig.js
frog/imports/ui/GraphEditor/SidePanel/ActivityPanel/EditActivity.js
frog/imports/ui/GraphEditor/SidePanel/ActivityPanel/addSocialSchema.js
frog/imports/ui/GraphEditor/SidePanel/OperatorPanel.js
op/op-prox/src/index.js

This PR fixes the bug that you cannot have empty configs - it checks for this in the graph validator, and it does not display the form element if there is no config. Also cleaned up slightly the code in Operator/Activity sidepanel.
Closes #404

Fixing bug and cleaning up

---

ac/ac-imgClass/src/imgClassifier.jsx
ac/ac-imgClass/src/index.js
ac/ac-imgView/src/ActivityRunner.jsx
ac/ac-imgView/src/components/CategoryBox.jsx
ac/ac-imgView/src/components/ImageBox.jsx
ac/ac-imgView/src/components/ThumbList.jsx
ac/ac-imgView/src/components/TopBar.jsx
ac/ac-imgView/src/index.js

• solve issues in mergeFunction (also in imgClassifier)
• voting and uploading became a config field
• changed ActivityRunner to class ext Component
• |_> replaced a lot of 'withState' with actual states
• unbind 'esc' in component will unmout
• replace the shift voting with a event.target.shiftKey instead of a Mousetrap

done ? flow error should be corrected with another PR

---

frog/imports/ui/GraphEditor/SidePanel/ActivityPanel/ChooseActivity.js
frog/imports/ui/GraphEditor/SidePanel/OperatorPanel.js
package-lock.json

In the ac/op choose panel:
ac choose panel => search bar was too long => wasn't possible to close the side panel with the button
(also augmented the size of the operator search bar and reduced the size of the list-items panel)

css details

---

frog/imports/ui/StudentView/Countdown.jsx
frog/imports/ui/StudentView/SessionBody.jsx
frog/imports/ui/StudentView/index.js

- Moves the countdown component to its own file and give it the currentTime props through createContainer.
- Update the style so the countdown is on top of mosaic windows and with fixed position
- small clean up on SessionBody compoennt
Closes #448
Closes #447

Countdown uses his own createContainer

---

ac/ac-form/src/config.js
frog-utils/src/types.js
op/op-create-groups/src/index.js
op/op-distribute/src/index.js
op/op-hypothesis/src/index.js

Just some small fixes to op-create-groups and op-hypothesis config definitions.

Small operator config fixes

---

frog/imports/ui/TeacherView/Dashboard.jsx

The problem is that I created the connection only when the activityId changes which is not the case when the component mounts the first time
Closes #454

Connects to the reactive data when component mounts

---

frog/imports/api/validGraphFn.js
frog/imports/ui/GraphEditor/store/activityStore.js
frog/imports/ui/GraphEditor/store/store.js

Add specific test for groupingKeys in validGraphFn

---

frog/imports/ui/TeacherView/StudentList.jsx
frog/server/api.js

Very small PR to update the LTI module to allow direct joining of sessions, and also to hide student names if there are more than 25 (I have not tested this yet, but I will once we can get containers to work).

Updating LTI and not showing student names if too many

---

frog/server/mergeLogData.js

This PR caches the log reactive document and the data function, to ensure that all log entries get processed properly.

Caching log reactive document

---

ac/ac-video/package.json

Updating ac-video package to make it work in Safari
Closes #485

Updating ac-video

---

ac/ac-quiz/src/ActivityRunner.jsx
ac/ac-quiz/src/Dashboard.jsx
ac/ac-quiz/src/index.js
frog-utils/src/types.js
frog/imports/ui/GraphEditor/Preview.js
frog/imports/ui/TeacherView/Dashboard.jsx

Not very beautiful, but functional. Shows how many instances selected each answer for each question.

Dashboard for ac-quiz

---

ac/ac-imgView/src/ActivityRunner.jsx
ac/ac-imgView/src/Dashboard.jsx
ac/ac-imgView/src/components/ThumbList.jsx
ac/ac-imgView/src/index.js
ac/ac-imgView/src/utils.js

Comes with a new graph push on the graph repo

Make more logs, more dashboard and trash feature

---

frog-utils/src/ActivityComponents/TableView.jsx
frog-utils/src/ActivityComponents/react-spreadsheet-component/spreadsheet.js

This fixes rendering trouble when switching from a table to another and allows to edit collaboratively a table

Unil monty collab

---

ac/ac-imgClass/src/Classifier.jsx
ac/ac-imgClass/src/components/ObjectList.jsx
ac/ac-monty/src/index.js
frog-utils/src/ActivityComponents/TableView.jsx
frog-utils/src/ActivityComponents/react-spreadsheet-component/spreadsheet.js

Unil classifier star

---

ac/ac-imgView/src/components/WebcamInterface.jsx
frog-utils/package.json
frog-utils/src/ActivityComponents/TableView.jsx
frog-utils/src/ActivityComponents/TreeView.jsx
frog-utils/src/ActivityComponents/react-spreadsheet-component/cell.js
frog-utils/src/ActivityComponents/react-spreadsheet-component/dispatcher.js
frog-utils/src/ActivityComponents/react-spreadsheet-component/helpers.js
frog-utils/src/ActivityComponents/react-spreadsheet-component/row.js
frog-utils/src/ActivityComponents/react-spreadsheet-component/spreadsheet.js
frog-utils/src/ReactiveText.js
frog-utils/src/__tests__/index.js
frog-utils/src/generateReactiveFn.js
frog-utils/src/index.js
frog-utils/src/types.js
yarn.lock

Trying to slowly merge Unil branch into develop, began only with frog-utils, to minimize Eslint/Flow etc errors. This code should be mainly independent, apart from one tiny thing I had to do in ac-imgView/components/webcam, which we'll fix when we merge that activity.

Merging only frog-utils from UNIL branch

---

create-Dockerfile.js
initial_setup_wo_meteor.sh

I made these changes to try to make it easier for students to install, but my experience showed me that it was not useful at all, reverting.

Improve initial_setup

---

.eslintrc-prettier.js
sharedb/test.js

Only on eslintTest / CI, not while editing a file.
Also ignoring sharedb files.

Make prettier problems into errors in ESLint

---

ac/ac-brainstorm/src/ActivityRunner.jsx
ac/ac-image/src/ActivityRunner.jsx
ac/ac-image/src/index.js
frog-utils/src/types.js
frog/server/mergeLogData.js

Remember the bug about subscription to sharedb that required restarting the server after the start of the activity for streams? I found the same thing happening for logs.
Also removes unnecessary config fields in ac-image

MergeLog sharedb connection

---

.eslintrc.js
ac/ac-quiz/src/__tests__/exportData.js
ac/ac-quiz/src/index.js
frog-utils/src/types.js
frog/imports/ui/TeacherView/ShowInfo.js
frog/package.json
yarn.lock

I'm planning to work more on this, but it should already be mergeable, if you want to look at it. 
I want to add export of a full graph (doing this for each activity, and packaging it up), as well as some whole graph tables, like user mapping in a CSV file.

Export data
